general {
    no_fade_in = true
    no_fade_out = true
    immediate_render = true
    grace = 0
    disable_loading = true
}

animations {
    enabled = false
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/wallpaper.jpg
    color = rgba(30, 30, 46, 1.0)
    blur_passes = 0
    blur_size = 0
    brightness = 1.0
}

# Time (Large and Bold)
label {
    monitor =
    text = <span font_weight="900">$TIME</span>
    color = rgba(238, 203, 175, 1.0)
    font_size = 220
    font_family = sans-serif
    position = 0, 150
    halign = center
    valign = center
}

# Minimalist Input Box
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(20, 20, 20, 0.6)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <i>Enter Password</i>
    check_color = rgba(166, 227, 161, 0.8)
    fail_color = rgba(243, 139, 168, 0.8)
    fail_text = <i>$FAIL ($ATTEMPTS)</i> 
    position = 0, -300
    halign = center
    valign = center
    rounding = 10
}
